## Sequences

Calling the function make_array on several values places them into an array, which is a kind of sequential collection. Below, we collect four different temperatures into an array called highs. These are the estimated average daily high temperatures over all land on Earth (in degrees Celsius) for the decades surrounding 1850, 1900, 1950, and 2000, respectively, expressed as deviations from the average absolute high temperature between 1951 and 1980, which was 14.48 degrees.

In [2]:
import pandas as pd
import numpy as np

In [6]:
baseline_high = 14.48
highs = np.array([baseline_high - 0.880, baseline_high - 0.093,
                   baseline_high + 0.105, baseline_high + 0.684])
highs

array([13.6  , 14.387, 14.585, 15.164])

sum function computes the sum of all values in a collection, and the len function computes its length. (That's the number of values we put in it.) Using them together, we can compute the average of a collection.

In [7]:
sum(highs)/len(highs)

14.434000000000001

## Arrays

Arrays can also contain strings or other types of values, but a single array can only contain a single kind of data. (It usually doesn't make sense to group together unlike data anyway.) For example:

In [9]:
english_parts_of_speech = np.array(["noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection"])
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'], dtype='<U12')

Returning to the temperature data, we create arrays of average daily high temperatures for the decades surrounding 1850, 1900, 1950, and 2000.

In [10]:
(9/5) * highs + 32

array([56.48  , 57.8966, 58.253 , 59.2952])

Arrays also have methods, which are functions that operate on the array values. The mean of a collection of numbers is its average value: the sum divided by the length. Each pair of parentheses in the examples below is part of a call expression; it's calling a function with no arguments to perform a computation on the array called highs.

In [11]:
highs.size

4

In [12]:
highs.sum()

57.736000000000004

In [13]:
highs.mean()

14.434000000000001

In [14]:
np.diff(highs)

array([0.787, 0.198, 0.579])

In [15]:
np.prod(highs)

43274.231214608

## Fuctions

In [16]:
np.sum(highs)

57.736000000000004

In [17]:
np.all(highs)

True

In [18]:
np.any(highs)

True

In [19]:
np.count_nonzero(highs)

4

In [20]:
np.diff(highs)

array([0.787, 0.198, 0.579])

In [21]:
np.round(highs)

array([14., 14., 15., 15.])

In [22]:
np.cumprod(highs)

array([1.36000000e+01, 1.95663200e+02, 2.85374777e+03, 4.32742312e+04])

In [23]:
np.cumsum(highs)

array([13.6  , 27.987, 42.572, 57.736])

In [24]:
np.exp(highs)

array([ 806129.75912399, 1770902.74507973, 2158663.8493677 ,
       3851603.06453344])

In [25]:
np.log(highs)

array([2.61006979, 2.66632502, 2.6799936 , 2.7189242 ])

In [26]:
np.sqrt(highs)

array([3.68781778, 3.79301991, 3.81903129, 3.8940981 ])

In [27]:
np.sort(highs)

array([13.6  , 14.387, 14.585, 15.164])

In [28]:
np.char.lower('my')

array('my', dtype='<U2')

In [29]:
np.char.upper('my')

array('MY', dtype='<U2')

In [30]:
np.char.strip('haritha')

array('haritha', dtype='<U7')

In [31]:
np.char.isalpha('haritha')


array(True)

In [32]:
np.char.isnumeric('haritha')

array(False)

In [33]:
name='haritha'

In [34]:
np.char.count(name,'h')

array(2)

In [35]:
np.char.find('h',name)

array(-1)

In [36]:
np.char.rfind('h',name)

array(-1)

In [37]:
np.char.startswith(name,'h')

array(True)

## Ranges 

A range is an array of numbers in increasing or decreasing order, each separated by a regular interval. Ranges are useful in a surprisingly large number of situations, so it's worthwhile to learn about them.

Ranges are defined using the np.arange function, which takes either one, two, or three arguments: a start, and end, and a 'step'.

If you pass one argument to np.arange, this becomes the end value, with start=0, step=1 assumed. Two arguments give the start and end with step=1 assumed. Three arguments give the start, end and step explicitly.

A range always includes its start value, but does not include its end value. It counts up by step, and it stops before it gets to the end.

np.arange(end): An array starting with 0 of incre

In [38]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [39]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [40]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

In [41]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

Example: Leibniz's formula for  π 
π=4⋅(1−13+15−17+19−111+…)

In [42]:
by_four_to_20 = np.arange(1, 20, 4)
by_four_to_20

array([ 1,  5,  9, 13, 17])

In [43]:
positive_term_denominators = np.arange(1, 10000, 4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [44]:
positive_terms = 1 / positive_term_denominators
positive_terms

array([1.00000000e+00, 2.00000000e-01, 1.11111111e-01, ...,
       1.00110121e-04, 1.00070049e-04, 1.00030009e-04])

In [45]:
negative_terms = 1 / (positive_term_denominators + 2)
negative_terms

array([3.33333333e-01, 1.42857143e-01, 9.09090909e-02, ...,
       1.00090081e-04, 1.00050025e-04, 1.00010001e-04])

In [46]:
4 * ( sum(positive_terms) - sum(negative_terms) )

3.1413926535917955

## More on Arrays 

For our first example, we return once more to the temperature data. This time, we create arrays of average daily high and low temperatures for the decades surrounding 1850, 1900, 1950, and 2000.

In [47]:
baseline_low = 3.00
lows = np.array([baseline_low - 0.872, baseline_low - 0.629,
                  baseline_low - 0.126, baseline_low + 0.728])
lows

array([2.128, 2.371, 2.874, 3.728])

In [48]:
np.array([
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
])

array([11.472, 12.016, 11.711, 11.436])

As when we converted an array of temperatures from Celsius to Fahrenheit, Python provides a much cleaner way to write this:

In [49]:
highs - lows

array([11.472, 12.016, 11.711, 11.436])

## Wallis' Formula for  π  π=2⋅(2/1⋅2/3⋅4/3⋅4/5⋅6/5⋅6/7…)

In [51]:
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

In [52]:
2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)

3.1415910827951143