In [1]:
#data type
type(abs)

builtin_function_or_method

In [2]:
type(45)

int

In [3]:
1 + 3

4

In [4]:
-1234567890000000000

-1234567890000000000

In [5]:
# Some float values
1.2

1.2

In [6]:
3.0

3.0

In [7]:
1.5 + 2

3.5

In [8]:
3 / 1


3.0

In [9]:
-12345678900000000000.0

-1.23456789e+19

In [10]:
type(3)

int

In [11]:
type(3 / 1)

float

In [12]:
x = 3
type(x)  # The type of x is an int, not a name

int

In [13]:
type(x + 2.5)

float

In [14]:
2e306 * 10

2e+307

In [15]:
2e306 * 100

inf

In [16]:
2e-322 / 10


2e-323

In [17]:
2e-322 / 100 #Large value so we get zero as output

0.0

In [18]:
0.6666666666666666 - 0.6666666666666666123456789

0.0

In [19]:
2 ** 0.5

1.4142135623730951

In [20]:
(2 ** 0.5) * (2 ** 0.5)

2.0000000000000004

In [21]:
(2 ** 0.5) * (2 ** 0.5) - 2

4.440892098500626e-16

In [22]:
"data" + "science"

'datascience'

In [23]:
"data" + " " + "science"

'data science'

In [24]:
"This won't work with a single-quoted string!"

"This won't work with a single-quoted string!"

In [25]:
"That's " + str(1 + 1) + ' ' + str(True)

"That's 2 True"

In [26]:
"loud".upper()

'LOUD'

In [27]:
'hitchhiker'.replace('hi', 'ma')

'matchmaker'

In [28]:
s = "train"
t = s.replace('t', 'ing')
u = t.replace('in', 'de')
u

'degrade'

In [29]:
s

'train'

In [30]:
3 > 1 + 1

True

In [31]:
1 < 1 + 1 < 3

True

In [32]:
x = 12
y = 5
min(x, y) <= (x+y)/2 <= max(x, y)

True

In [33]:
"Dog" > "Catastrophe" > "Cat"

True

In [34]:
import numpy as np

In [35]:
##Sequences 
baseline_high = 14.48
highs = np.array([[baseline_high - 0.880], [baseline_high - 0.093],
                   [baseline_high + 0.105], [baseline_high + 0.684]])
highs

array([[13.6  ],
       [14.387],
       [14.585],
       [15.164]])

In [36]:
baseline_high = 14.48
highs = np.array([baseline_high - 0.880, baseline_high - 0.093,
                   baseline_high + 0.105, baseline_high + 0.684])
highs

array([13.6  , 14.387, 14.585, 15.164])

In [37]:
sum(highs)/len(highs)

14.434000000000001

In [38]:
#Arrays
english_parts_of_speech = np.array(["noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection"])
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'], dtype='<U12')

In [39]:
(9/5) * highs + 32

array([56.48  , 57.8966, 58.253 , 59.2952])

In [40]:
highs.size

4

In [41]:
highs.sum()

57.736000000000004

In [42]:
highs.mean()

14.434000000000001

In [43]:
np.diff(highs)

array([0.787, 0.198, 0.579])

## Fuctions

In [44]:
np.prod(highs)

43274.231214608

In [45]:
np.sum(highs)

57.736000000000004

In [46]:
np.all(highs)

True

In [47]:
np.any(highs)

True

In [48]:
np.count_nonzero(highs)

4

In [49]:
np.diff(highs)

array([0.787, 0.198, 0.579])

In [50]:
np.round(highs)

array([14., 14., 15., 15.])

In [51]:
np.cumprod(highs)

array([1.36000000e+01, 1.95663200e+02, 2.85374777e+03, 4.32742312e+04])

In [52]:
np.cumsum(highs)

array([13.6  , 27.987, 42.572, 57.736])

In [53]:
np.exp(highs)

array([ 806129.75912399, 1770902.74507973, 2158663.8493677 ,
       3851603.06453344])

In [54]:
np.log(highs)

array([2.61006979, 2.66632502, 2.6799936 , 2.7189242 ])

In [55]:
np.sqrt(highs)

array([3.68781778, 3.79301991, 3.81903129, 3.8940981 ])

In [56]:
np.sort(highs)

array([13.6  , 14.387, 14.585, 15.164])

In [57]:
np.char.lower('my')

array('my', dtype='<U2')

In [58]:
np.char.upper('my')

array('MY', dtype='<U2')

In [59]:
np.char.strip('haritha')

array('haritha', dtype='<U7')

In [60]:
np.char.isalpha('haritha')

array(True)

In [61]:
np.char.isnumeric('haritha')

array(False)

In [62]:
name='haritha'

In [63]:
np.char.count(name,'h')

array(2)

In [64]:
np.char.find('h',name)

array(-1)

In [65]:
np.char.rfind('h',name)

array(-1)

In [66]:
np.char.startswith(name,'h')

array(True)

In [67]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [68]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [69]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

In [70]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

Trying with Leibniz's formula for  π   π=4⋅(1−13+15−17+19−111+…)

In [71]:
by_four_to_20 = np.arange(1, 20, 4)
by_four_to_20

array([ 1,  5,  9, 13, 17])

In [72]:
positive_term_denominators = np.arange(1, 10000, 4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [73]:
positive_terms = 1 / positive_term_denominators
positive_terms

array([1.00000000e+00, 2.00000000e-01, 1.11111111e-01, ...,
       1.00110121e-04, 1.00070049e-04, 1.00030009e-04])

In [74]:
negative_terms = 1 / (positive_term_denominators + 2)
negative_terms

array([3.33333333e-01, 1.42857143e-01, 9.09090909e-02, ...,
       1.00090081e-04, 1.00050025e-04, 1.00010001e-04])

In [75]:
4 * ( sum(positive_terms) - sum(negative_terms) )

3.1413926535917955

In [76]:
baseline_high = 14.48
highs = np.array([baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684])
highs

array([13.6  , 14.387, 14.585, 15.164])

In [77]:
baseline_low = 3.00
lows = np.array([baseline_low - 0.872, baseline_low - 0.629,
                  baseline_low - 0.126, baseline_low + 0.728])
lows

array([2.128, 2.371, 2.874, 3.728])

In [78]:
np.array([
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
])

array([11.472, 12.016, 11.711, 11.436])

In [79]:
highs - lows

array([11.472, 12.016, 11.711, 11.436])

In [80]:
#Wallis' Formula for  π  π=2⋅(2/1⋅2/3⋅4/3⋅4/5⋅6/5⋅6/7…)

In [81]:
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

In [82]:
2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)

3.1415910827951143

In [83]:
import pandas as pd 

In [84]:
df = pd.DataFrame() 

In [85]:
df['Name'] = ['Ankit', 'Ankita', 'Yashvardhan'] 
df['Articles'] = [97, 600, 200] 
df['Improved'] = [2200, 75, 100] 

In [86]:
df 

Name  Articles  Improved
0        Ankit        97      2200
1       Ankita       600        75
2  Yashvardhan       200       100

In [87]:
data=[8,34,5]

In [88]:
df = pd.DataFrame(data, columns = ['Number of Petals']) 

In [89]:
df

Number of Petals
0                 8
1                34
2                 5

In [90]:
df1 = pd.DataFrame() 

In [91]:
df1['Number of Petals'] = [8,34,5]
df1['Name'] = ['lotus', 'sunflower', 'rose'] 

In [92]:
df1

Number of Petals       Name
0                 8      lotus
1                34  sunflower
2                 5       rose

In [93]:
df1['Number of Petals'] = [8,34,5]
df1['Name'] = ['lotus', 'sunflower', 'rose'] 
df1['Color'] = ['pink', 'yellow', 'red']


In [94]:
df1

Number of Petals       Name   Color
0                 8      lotus    pink
1                34  sunflower  yellow
2                 5       rose     red

In [95]:
df =pd.read_csv('minard.csv') 
df

Longitude  Latitude         City Direction  Survivors
0       32.0      54.8     Smolensk   Advance     145000
1       33.2      54.9  Dorogobouge   Advance     140000
2       34.4      55.5        Chjat   Advance     127100
3       37.6      55.8       Moscou   Advance     100000
4       34.3      55.2        Wixma   Retreat      55000
5       32.0      54.6     Smolensk   Retreat      24000
6       30.4      54.4       Orscha   Retreat      20000
7       26.8      54.3    Moiodexno   Retreat      12000

In [96]:
df.shape

(8, 5)

In [97]:
df.columns


Index(['Longitude', 'Latitude', 'City', 'Direction', 'Survivors'], dtype='object')

In [98]:
list(df.columns)

['Longitude', 'Latitude', 'City', 'Direction', 'Survivors']

In [99]:
rows,columns=df.shape

In [100]:
rows

8

In [101]:
columns


5

In [102]:
df_new = df.rename(columns={'City': 'Cityname'})
df_new

Longitude  Latitude     Cityname Direction  Survivors
0       32.0      54.8     Smolensk   Advance     145000
1       33.2      54.9  Dorogobouge   Advance     140000
2       34.4      55.5        Chjat   Advance     127100
3       37.6      55.8       Moscou   Advance     100000
4       34.3      55.2        Wixma   Retreat      55000
5       32.0      54.6     Smolensk   Retreat      24000
6       30.4      54.4       Orscha   Retreat      20000
7       26.8      54.3    Moiodexno   Retreat      12000

In [103]:
#Accesing elements using row and column numbers
df.iat[2,2]  

'Chjat'

In [104]:
df.iat[7,4]  

12000

In [105]:
#Accesing elements using row and column numbers
df.iat[2,2] 

'Chjat'

In [106]:
df ['Latitude']

0    54.8
1    54.9
2    55.5
3    55.8
4    55.2
5    54.6
6    54.4
7    54.3
Name: Latitude, dtype: float64

## Working with the Data in a Column

In [107]:
initial = df.Survivors


In [108]:
initial

0    145000
1    140000
2    127100
3    100000
4     55000
5     24000
6     20000
7     12000
Name: Survivors, dtype: int64

In [109]:
 df.iloc[3]['City']


'Moscou'

In [110]:
####percent=(intial*100)
Finding percentage

SyntaxError: invalid syntax (<ipython-input-110-99833de42140>, line 2)

In [111]:
initial=df.Survivors
initial

0    145000
1    140000
2    127100
3    100000
4     55000
5     24000
6     20000
7     12000
Name: Survivors, dtype: int64

In [112]:
mean=df

In [113]:
p=df.iloc[0]['Survivors']
percentage=(initial/p)*100

In [114]:
df['Percentage'] = percentage
df

Longitude  Latitude         City Direction  Survivors  Percentage
0       32.0      54.8     Smolensk   Advance     145000  100.000000
1       33.2      54.9  Dorogobouge   Advance     140000   96.551724
2       34.4      55.5        Chjat   Advance     127100   87.655172
3       37.6      55.8       Moscou   Advance     100000   68.965517
4       34.3      55.2        Wixma   Retreat      55000   37.931034
5       32.0      54.6     Smolensk   Retreat      24000   16.551724
6       30.4      54.4       Orscha   Retreat      20000   13.793103
7       26.8      54.3    Moiodexno   Retreat      12000    8.275862

In [115]:
df[['City','Survivors']]

City  Survivors
0     Smolensk     145000
1  Dorogobouge     140000
2        Chjat     127100
3       Moscou     100000
4        Wixma      55000
5     Smolensk      24000
6       Orscha      20000
7    Moiodexno      12000

In [116]:
p=df.iloc[2][3]
p

'Advance'

In [117]:
df.City

0       Smolensk
1    Dorogobouge
2          Chjat
3         Moscou
4          Wixma
5       Smolensk
6         Orscha
7      Moiodexno
Name: City, dtype: object

In [118]:
df[['City']]

City
0     Smolensk
1  Dorogobouge
2        Chjat
3       Moscou
4        Wixma
5     Smolensk
6       Orscha
7    Moiodexno

In [119]:
df1=df.copy()
df1.drop(['City'],axis=1)
df1

Longitude  Latitude         City Direction  Survivors  Percentage
0       32.0      54.8     Smolensk   Advance     145000  100.000000
1       33.2      54.9  Dorogobouge   Advance     140000   96.551724
2       34.4      55.5        Chjat   Advance     127100   87.655172
3       37.6      55.8       Moscou   Advance     100000   68.965517
4       34.3      55.2        Wixma   Retreat      55000   37.931034
5       32.0      54.6     Smolensk   Retreat      24000   16.551724
6       30.4      54.4       Orscha   Retreat      20000   13.793103
7       26.8      54.3    Moiodexno   Retreat      12000    8.275862

### Sorting Rows

In [120]:
p=df.iloc[3][:]
p

Longitude        37.6
Latitude         55.8
City           Moscou
Direction     Advance
Survivors      100000
Percentage    68.9655
Name: 3, dtype: object

In [121]:
print(df.iloc[[3]])

   Longitude  Latitude    City Direction  Survivors  Percentage
3       37.6      55.8  Moscou   Advance     100000   68.965517


In [122]:
print(df.iloc[:],[1,4])

   Longitude  Latitude         City Direction  Survivors  Percentage
0       32.0      54.8     Smolensk   Advance     145000  100.000000
1       33.2      54.9  Dorogobouge   Advance     140000   96.551724
2       34.4      55.5        Chjat   Advance     127100   87.655172
3       37.6      55.8       Moscou   Advance     100000   68.965517
4       34.3      55.2        Wixma   Retreat      55000   37.931034
5       32.0      54.6     Smolensk   Retreat      24000   16.551724
6       30.4      54.4       Orscha   Retreat      20000   13.793103
7       26.8      54.3    Moiodexno   Retreat      12000    8.275862 [1, 4]


In [123]:
n=df.sort_values(by=['Percentage'], inplace=True)

In [124]:
df


Longitude  Latitude         City Direction  Survivors  Percentage
7       26.8      54.3    Moiodexno   Retreat      12000    8.275862
6       30.4      54.4       Orscha   Retreat      20000   13.793103
5       32.0      54.6     Smolensk   Retreat      24000   16.551724
4       34.3      55.2        Wixma   Retreat      55000   37.931034
3       37.6      55.8       Moscou   Advance     100000   68.965517
2       34.4      55.5        Chjat   Advance     127100   87.655172
1       33.2      54.9  Dorogobouge   Advance     140000   96.551724
0       32.0      54.8     Smolensk   Advance     145000  100.000000

In [125]:
df_new = df.rename(columns={'Longitude': 'La'}, index={'City': 'city'})
df_new

La  Latitude         City Direction  Survivors  Percentage
7  26.8      54.3    Moiodexno   Retreat      12000    8.275862
6  30.4      54.4       Orscha   Retreat      20000   13.793103
5  32.0      54.6     Smolensk   Retreat      24000   16.551724
4  34.3      55.2        Wixma   Retreat      55000   37.931034
3  37.6      55.8       Moscou   Advance     100000   68.965517
2  34.4      55.5        Chjat   Advance     127100   87.655172
1  33.2      54.9  Dorogobouge   Advance     140000   96.551724
0  32.0      54.8     Smolensk   Advance     145000  100.000000

In [126]:
n=df.sort_values(by=['Percentage'], ascending=False)
n

Longitude  Latitude         City Direction  Survivors  Percentage
0       32.0      54.8     Smolensk   Advance     145000  100.000000
1       33.2      54.9  Dorogobouge   Advance     140000   96.551724
2       34.4      55.5        Chjat   Advance     127100   87.655172
3       37.6      55.8       Moscou   Advance     100000   68.965517
4       34.3      55.2        Wixma   Retreat      55000   37.931034
5       32.0      54.6     Smolensk   Retreat      24000   16.551724
6       30.4      54.4       Orscha   Retreat      20000   13.793103
7       26.8      54.3    Moiodexno   Retreat      12000    8.275862

In [127]:
n=df.sort_values(by=['Percentage'], ascending=True)
n

Longitude  Latitude         City Direction  Survivors  Percentage
7       26.8      54.3    Moiodexno   Retreat      12000    8.275862
6       30.4      54.4       Orscha   Retreat      20000   13.793103
5       32.0      54.6     Smolensk   Retreat      24000   16.551724
4       34.3      55.2        Wixma   Retreat      55000   37.931034
3       37.6      55.8       Moscou   Advance     100000   68.965517
2       34.4      55.5        Chjat   Advance     127100   87.655172
1       33.2      54.9  Dorogobouge   Advance     140000   96.551724
0       32.0      54.8     Smolensk   Advance     145000  100.000000

In [128]:
df.iloc[[4]]

Longitude  Latitude    City Direction  Survivors  Percentage
3       37.6      55.8  Moscou   Advance     100000   68.965517

In [129]:
df.iloc[[1,4]]

Longitude  Latitude    City Direction  Survivors  Percentage
6       30.4      54.4  Orscha   Retreat      20000   13.793103
3       37.6      55.8  Moscou   Advance     100000   68.965517

In [130]:
m=df.sort_values(by=['Survivors'], ascending=True)
m

Longitude  Latitude         City Direction  Survivors  Percentage
7       26.8      54.3    Moiodexno   Retreat      12000    8.275862
6       30.4      54.4       Orscha   Retreat      20000   13.793103
5       32.0      54.6     Smolensk   Retreat      24000   16.551724
4       34.3      55.2        Wixma   Retreat      55000   37.931034
3       37.6      55.8       Moscou   Advance     100000   68.965517
2       34.4      55.5        Chjat   Advance     127100   87.655172
1       33.2      54.9  Dorogobouge   Advance     140000   96.551724
0       32.0      54.8     Smolensk   Advance     145000  100.000000

In [131]:
df.iloc[[1,5]]

Longitude  Latitude    City Direction  Survivors  Percentage
6       30.4      54.4  Orscha   Retreat      20000   13.793103
2       34.4      55.5   Chjat   Advance     127100   87.655172

In [132]:
df['City']

7      Moiodexno
6         Orscha
5       Smolensk
4          Wixma
3         Moscou
2          Chjat
1    Dorogobouge
0       Smolensk
Name: City, dtype: object

In [133]:
df.City

7      Moiodexno
6         Orscha
5       Smolensk
4          Wixma
3         Moscou
2          Chjat
1    Dorogobouge
0       Smolensk
Name: City, dtype: object

In [134]:
df['Percentage'].sort_values

<bound method Series.sort_values of 7      8.275862
6     13.793103
5     16.551724
4     37.931034
3     68.965517
2     87.655172
1     96.551724
0    100.000000
Name: Percentage, dtype: float64>

In [135]:
n=df.sort_values(by=['Percentage'], ascending=False)
n

Longitude  Latitude         City Direction  Survivors  Percentage
0       32.0      54.8     Smolensk   Advance     145000  100.000000
1       33.2      54.9  Dorogobouge   Advance     140000   96.551724
2       34.4      55.5        Chjat   Advance     127100   87.655172
3       37.6      55.8       Moscou   Advance     100000   68.965517
4       34.3      55.2        Wixma   Retreat      55000   37.931034
5       32.0      54.6     Smolensk   Retreat      24000   16.551724
6       30.4      54.4       Orscha   Retreat      20000   13.793103
7       26.8      54.3    Moiodexno   Retreat      12000    8.275862

nba.where('PLAYER', are.equal_to('Stephen Curry'))

In [136]:
df["Indexes"]= df['City'].str.find('Wixma') 
df["Indexes"]

7   -1
6   -1
5   -1
4    0
3   -1
2   -1
1   -1
0   -1
Name: Indexes, dtype: int64

In [137]:
df["Indexes"]= df.City.str.find('Wixma' )
df["Indexes"]

7   -1
6   -1
5   -1
4    0
3   -1
2   -1
1   -1
0   -1
Name: Indexes, dtype: int64

In [138]:
#Here "Chjat get replaced by zero
df["City"]= df["City"].str.replace("Orscha", "zero", case = False) 
  
df["City"]

7      Moiodexno
6           zero
5       Smolensk
4          Wixma
3         Moscou
2          Chjat
1    Dorogobouge
0       Smolensk
Name: City, dtype: object

In [139]:
filter = df["City"]=="New Boston Celtics"
  
df.where(df[filter]).dropna() 

Empty DataFrame
Columns: [Longitude, Latitude, City, Direction, Survivors, Percentage, Indexes]
Index: []

### Multiple Features 

In [140]:
data=pd.read_csv('n.csv')

In [141]:
data

SEX  AGE  CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
0      0    0        3944153            3944160          3951330   
1      0    1        3978070            3978090          3957888   
2      0    2        4096929            4096939          4090862   
3      0    3        4119040            4119051          4111920   
4      0    4        4063170            4063186          4077551   
..   ...  ...            ...                ...              ...   
301    2   97          53582              53605            54118   
302    2   98          36641              36675            37532   
303    2   99          26193              26214            26074   
304    2  100          44202              44246            45058   
305    2  999      156964212          156969328        157258820   

     POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  POPESTIMATE2014  \
0            3963087          3926540          3931141          3949775   
1            3966551          3977939          3942872          3949776   
2            3971565          3980095          3992720          3959664   
3            4102470          3983157          3992734          4007079   
4            4122294          4112849          3994449          4005716   
..               ...              ...              ...              ...   
301            57159            59533            61255            62779   
302            40116            42857            44359            46208   
303            27030            29320            31112            32517   
304            47556            50661            53902            58008   
305        158427085        159581546        160720625        161952064   

     POPESTIMATE2015  
0            3978038  
1            3968564  
2            3966583  
3            3974061  
4            4020035  
..               ...  
301            69285  
302            47272  
303            34064  
304            61886  
305        163189523  

[306 rows x 10 columns]

In [142]:
p = data[['SEX', 'AGE', 'POPESTIMATE2010', 'POPESTIMATE2014']]


In [143]:
p

SEX  AGE  POPESTIMATE2010  POPESTIMATE2014
0      0    0          3951330          3949775
1      0    1          3957888          3949776
2      0    2          4090862          3959664
3      0    3          4111920          4007079
4      0    4          4077551          4005716
..   ...  ...              ...              ...
301    2   97            54118            62779
302    2   98            37532            46208
303    2   99            26074            32517
304    2  100            45058            58008
305    2  999        157258820        161952064

[306 rows x 4 columns]

In [144]:
data_new = data.rename(columns={'Sex': 'sex'}, index={'Age': 'A'})


In [145]:
data_new 

SEX  AGE  CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
0      0    0        3944153            3944160          3951330   
1      0    1        3978070            3978090          3957888   
2      0    2        4096929            4096939          4090862   
3      0    3        4119040            4119051          4111920   
4      0    4        4063170            4063186          4077551   
..   ...  ...            ...                ...              ...   
301    2   97          53582              53605            54118   
302    2   98          36641              36675            37532   
303    2   99          26193              26214            26074   
304    2  100          44202              44246            45058   
305    2  999      156964212          156969328        157258820   

     POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  POPESTIMATE2014  \
0            3963087          3926540          3931141          3949775   
1            3966551          3977939          3942872          3949776   
2            3971565          3980095          3992720          3959664   
3            4102470          3983157          3992734          4007079   
4            4122294          4112849          3994449          4005716   
..               ...              ...              ...              ...   
301            57159            59533            61255            62779   
302            40116            42857            44359            46208   
303            27030            29320            31112            32517   
304            47556            50661            53902            58008   
305        158427085        159581546        160720625        161952064   

     POPESTIMATE2015  
0            3978038  
1            3968564  
2            3966583  
3            3974061  
4            4020035  
..               ...  
301            69285  
302            47272  
303            34064  
304            61886  
305        163189523  

[306 rows x 10 columns]

In [146]:
change=data.CENSUS2010POP-data.ESTIMATESBASE2010

In [147]:
change

0        -7
1       -20
2       -10
3       -11
4       -16
       ... 
301     -23
302     -34
303     -21
304     -44
305   -5116
Length: 306, dtype: int64

In [148]:
percentage_change=change/data.ESTIMATESBASE2010
percentage_change

0     -0.000002
1     -0.000005
2     -0.000002
3     -0.000003
4     -0.000004
         ...   
301   -0.000429
302   -0.000927
303   -0.000801
304   -0.000994
305   -0.000033
Length: 306, dtype: float64

In [149]:
data['percentage']=percentage_change
data

SEX  AGE  CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
0      0    0        3944153            3944160          3951330   
1      0    1        3978070            3978090          3957888   
2      0    2        4096929            4096939          4090862   
3      0    3        4119040            4119051          4111920   
4      0    4        4063170            4063186          4077551   
..   ...  ...            ...                ...              ...   
301    2   97          53582              53605            54118   
302    2   98          36641              36675            37532   
303    2   99          26193              26214            26074   
304    2  100          44202              44246            45058   
305    2  999      156964212          156969328        157258820   

     POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  POPESTIMATE2014  \
0            3963087          3926540          3931141          3949775   
1            3966551          3977939          3942872          3949776   
2            3971565          3980095          3992720          3959664   
3            4102470          3983157          3992734          4007079   
4            4122294          4112849          3994449          4005716   
..               ...              ...              ...              ...   
301            57159            59533            61255            62779   
302            40116            42857            44359            46208   
303            27030            29320            31112            32517   
304            47556            50661            53902            58008   
305        158427085        159581546        160720625        161952064   

     POPESTIMATE2015  percentage  
0            3978038   -0.000002  
1            3968564   -0.000005  
2            3966583   -0.000002  
3            3974061   -0.000003  
4            4020035   -0.000004  
..               ...         ...  
301            69285   -0.000429  
302            47272   -0.000927  
303            34064   -0.000801  
304            61886   -0.000994  
305        163189523   -0.000033  

[306 rows x 11 columns]

In [150]:
data['percentage'].sort_values

<bound method Series.sort_values of 0     -0.000002
1     -0.000005
2     -0.000002
3     -0.000003
4     -0.000004
         ...   
301   -0.000429
302   -0.000927
303   -0.000801
304   -0.000994
305   -0.000033
Name: percentage, Length: 306, dtype: float64>

In [151]:
data

SEX  AGE  CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
0      0    0        3944153            3944160          3951330   
1      0    1        3978070            3978090          3957888   
2      0    2        4096929            4096939          4090862   
3      0    3        4119040            4119051          4111920   
4      0    4        4063170            4063186          4077551   
..   ...  ...            ...                ...              ...   
301    2   97          53582              53605            54118   
302    2   98          36641              36675            37532   
303    2   99          26193              26214            26074   
304    2  100          44202              44246            45058   
305    2  999      156964212          156969328        157258820   

     POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  POPESTIMATE2014  \
0            3963087          3926540          3931141          3949775   
1            3966551          3977939          3942872          3949776   
2            3971565          3980095          3992720          3959664   
3            4102470          3983157          3992734          4007079   
4            4122294          4112849          3994449          4005716   
..               ...              ...              ...              ...   
301            57159            59533            61255            62779   
302            40116            42857            44359            46208   
303            27030            29320            31112            32517   
304            47556            50661            53902            58008   
305        158427085        159581546        160720625        161952064   

     POPESTIMATE2015  percentage  
0            3978038   -0.000002  
1            3968564   -0.000005  
2            3966583   -0.000002  
3            3974061   -0.000003  
4            4020035   -0.000004  
..               ...         ...  
301            69285   -0.000429  
302            47272   -0.000927  
303            34064   -0.000801  
304            61886   -0.000994  
305        163189523   -0.000033  

[306 rows x 11 columns]

In [160]:
data['Age'].sort_values

KeyError: 'Age'

In [ ]:
print(data.loc[data['CENSUS2010POP'] == 26193]['A'].index.values)